/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Users {
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface Member {
  id: string;
  organization_id: string;
  user_id: string;
  role: string;
  created_at: Timestamp;
}

export interface Organization {
  id: string;
  name: string;
  slug: string;
  logo: string | null;
  created_at: Timestamp;
  metadata: string | null;
}

export interface DB {
  users: Users;
  member: Member;
  organization: Organization;
}
