/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizationAcceptInvitationRouteImport } from './routes/organization/accept-invitation'
import { Route as AuthOrgsIndexRouteImport } from './routes/_auth/orgs/index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin/index'
import { Route as AuthOrgsOrgIdRouteImport } from './routes/_auth/orgs/$orgId'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin/admin/users'
import { Route as AuthOrgsOrgIdIndexRouteImport } from './routes/_auth/orgs/$orgId/index'
import { Route as AuthOrgsOrgIdSettingsRouteImport } from './routes/_auth/orgs/$orgId/settings'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationAcceptInvitationRoute =
  OrganizationAcceptInvitationRouteImport.update({
    id: '/organization/accept-invitation',
    path: '/organization/accept-invitation',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthOrgsIndexRoute = AuthOrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => AuthRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const AuthOrgsOrgIdRoute = AuthOrgsOrgIdRouteImport.update({
  id: '/orgs/$orgId',
  path: '/orgs/$orgId',
  getParentRoute: () => AuthRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AdminRoute,
} as any)
const AuthOrgsOrgIdIndexRoute = AuthOrgsOrgIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthOrgsOrgIdRoute,
} as any)
const AuthOrgsOrgIdSettingsRoute = AuthOrgsOrgIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthOrgsOrgIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/organization/accept-invitation': typeof OrganizationAcceptInvitationRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/orgs/$orgId': typeof AuthOrgsOrgIdRouteWithChildren
  '/admin': typeof AdminAdminIndexRoute
  '/orgs': typeof AuthOrgsIndexRoute
  '/orgs/$orgId/settings': typeof AuthOrgsOrgIdSettingsRoute
  '/orgs/$orgId/': typeof AuthOrgsOrgIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/organization/accept-invitation': typeof OrganizationAcceptInvitationRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/admin': typeof AdminAdminIndexRoute
  '/orgs': typeof AuthOrgsIndexRoute
  '/orgs/$orgId/settings': typeof AuthOrgsOrgIdSettingsRoute
  '/orgs/$orgId': typeof AuthOrgsOrgIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/organization/accept-invitation': typeof OrganizationAcceptInvitationRoute
  '/_admin/admin/users': typeof AdminAdminUsersRoute
  '/_auth/orgs/$orgId': typeof AuthOrgsOrgIdRouteWithChildren
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_auth/orgs/': typeof AuthOrgsIndexRoute
  '/_auth/orgs/$orgId/settings': typeof AuthOrgsOrgIdSettingsRoute
  '/_auth/orgs/$orgId/': typeof AuthOrgsOrgIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/organization/accept-invitation'
    | '/admin/users'
    | '/orgs/$orgId'
    | '/admin'
    | '/orgs'
    | '/orgs/$orgId/settings'
    | '/orgs/$orgId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/organization/accept-invitation'
    | '/admin/users'
    | '/admin'
    | '/orgs'
    | '/orgs/$orgId/settings'
    | '/orgs/$orgId'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_auth'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/organization/accept-invitation'
    | '/_admin/admin/users'
    | '/_auth/orgs/$orgId'
    | '/_admin/admin/'
    | '/_auth/orgs/'
    | '/_auth/orgs/$orgId/settings'
    | '/_auth/orgs/$orgId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  OrganizationAcceptInvitationRoute: typeof OrganizationAcceptInvitationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/accept-invitation': {
      id: '/organization/accept-invitation'
      path: '/organization/accept-invitation'
      fullPath: '/organization/accept-invitation'
      preLoaderRoute: typeof OrganizationAcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/orgs/': {
      id: '/_auth/orgs/'
      path: '/orgs'
      fullPath: '/orgs'
      preLoaderRoute: typeof AuthOrgsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_auth/orgs/$orgId': {
      id: '/_auth/orgs/$orgId'
      path: '/orgs/$orgId'
      fullPath: '/orgs/$orgId'
      preLoaderRoute: typeof AuthOrgsOrgIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_auth/orgs/$orgId/': {
      id: '/_auth/orgs/$orgId/'
      path: '/'
      fullPath: '/orgs/$orgId/'
      preLoaderRoute: typeof AuthOrgsOrgIdIndexRouteImport
      parentRoute: typeof AuthOrgsOrgIdRoute
    }
    '/_auth/orgs/$orgId/settings': {
      id: '/_auth/orgs/$orgId/settings'
      path: '/settings'
      fullPath: '/orgs/$orgId/settings'
      preLoaderRoute: typeof AuthOrgsOrgIdSettingsRouteImport
      parentRoute: typeof AuthOrgsOrgIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthOrgsOrgIdRouteChildren {
  AuthOrgsOrgIdSettingsRoute: typeof AuthOrgsOrgIdSettingsRoute
  AuthOrgsOrgIdIndexRoute: typeof AuthOrgsOrgIdIndexRoute
}

const AuthOrgsOrgIdRouteChildren: AuthOrgsOrgIdRouteChildren = {
  AuthOrgsOrgIdSettingsRoute: AuthOrgsOrgIdSettingsRoute,
  AuthOrgsOrgIdIndexRoute: AuthOrgsOrgIdIndexRoute,
}

const AuthOrgsOrgIdRouteWithChildren = AuthOrgsOrgIdRoute._addFileChildren(
  AuthOrgsOrgIdRouteChildren,
)

interface AuthRouteChildren {
  AuthOrgsOrgIdRoute: typeof AuthOrgsOrgIdRouteWithChildren
  AuthOrgsIndexRoute: typeof AuthOrgsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthOrgsOrgIdRoute: AuthOrgsOrgIdRouteWithChildren,
  AuthOrgsIndexRoute: AuthOrgsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  OrganizationAcceptInvitationRoute: OrganizationAcceptInvitationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
